# Generated by Django 5.1.7 on 2025-03-30 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('Netflix', 'Netflix'), ('Spotify', 'Spotify'), ('YouTube', 'YouTube Premium'), ('Other', 'Басқа')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_date', models.DateField()),
                ('reminder_days_before', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
